### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by Holeryn** [reds-heig/logisim-evolution#358]
After git cloned the repo and did :
`./gradelw run`
I receive this:

```
Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:198)
	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:205)
	at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1004)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1372)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.security.Provider$Service.newInstance(Provider.java:1256)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:994)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:62)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: sun/security/ec/ECParameters
	at sun.security.pkcs11.SunPKCS11$P11Service.newInstance0(SunPKCS11.java:1038)
	at sun.security.pkcs11.SunPKCS11$P11Service.newInstance(SunPKCS11.java:980)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:694)
	at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:121)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:167)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:699)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:166)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1806)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:197)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:98)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:760)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1381)
	at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226)
	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:869)
	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:847)
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1006)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.security.Provider$Service.newInstance(Provider.java:1237)
	... 19 more
Caused by: java.lang.ClassNotFoundException: sun.security.ec.ECParameters
	at java.net.URLClassLoader$1.run(URLClassLoader.java:360)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	... 50 more
```
Instead if i try to start the pre compiled build with:
`java -jar logisim-evolution.jar `
I receive this:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.cburch.logisim.gui.start.Startup.parseArgs(Unknown Source)
	at com.cburch.logisim.Main.main(Unknown Source)
Caused by: java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:282)
	at com.cburch.logisim.prefs.AppPreferences.<clinit>(Unknown Source)
	... 2 more
```

**Comment by Holeryn** [comment]
I did :
```
sudo pacman -S java-runtime-common
sudo pacman -S java-environment-common
```
and after installed this packages, in could execute logisim
