### ISSUE TITLE
Test Vector file with invalid bit width throws exception

### ISSUE THREAD

**Issue by simoc** [reds-heig/logisim-evolution#502]
If a test vector file with an invalid bit width such as `O[2.0]` or `O[[]` is loaded using the Simulate -> Test Vector -> Load Vector button, then logisim throws a java exception. No output is displayed in the Test Vector window and no error dialog is displayed.

My example test vector file with an invalid bit width is:

    A B O[2.0]
    0 0 00
    0 1 01
    1 0 10
    1 1 11

Java exception is:

    Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "2.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.<init>(Integer.java:1111)
	at com.cburch.logisim.data.TestVector$TestVectorReader.parseHeader(TestVector.java:134)
	at com.cburch.logisim.data.TestVector$TestVectorReader.parse(TestVector.java:86)
	at com.cburch.logisim.data.TestVector.<init>(TestVector.java:155)
        at com.cburch.logisim.gui.test.TestFrame$MyListener.actionPerformed(TestFrame.java:197)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)

I am using the `develop` git branch of logisim-evolution.

**Comment by simoc** [comment]
Fixed by #503. I am closing this issue manually.
