### ISSUE TITLE
Java exception when deleting variable from Combinatorial Analysis

### ISSUE THREAD

**Issue by simoc** [reds-heig/logisim-evolution#511]
I opened the Combinatorial Analysis window and added two Input Variables `A` and `B`. I clicked on the `A` to highlight it, then pressed `Delete` to delete this variable. Logisim reports a java exception in the terminal window and the variable `A` is still visible (`A` does disappear after adding another variable).

The java exception is:

    Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.cburch.logisim.analyze.model.TruthTable$MyListener.removeInput(TruthTable.java:664)
	at com.cburch.logisim.analyze.model.TruthTable$MyListener.inputsChanged(TruthTable.java:586)
	at com.cburch.logisim.analyze.model.TruthTable$MyListener.listChanged(TruthTable.java:524)
	at com.cburch.logisim.analyze.model.VariableList.fireEvent(VariableList.java:99)
	at com.cburch.logisim.analyze.model.VariableList.remove(VariableList.java:137)
	at com.cburch.logisim.analyze.gui.VariableTab$3.actionPerformed(VariableTab.java:132)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JTable.processKeyBinding(JTable.java:5264)
    ...

I am using the `develop` git branch.

**Comment by simoc** [comment]
Fixed by #513. I am closing this issue manually.
